/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 *
 * @author e.zimmermann
 */
public class UpdateUserDialog extends javax.swing.JDialog {

    //Atribut
    private int id;
    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    //Constructeur
    //Methode
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        listeners.addPropertyChangeListener(listener);
    }

    //Get
    public int getId() {
        return this.id;
    }

    public String getPrenom() {
        return this.updatePrenomUser.getText();
    }

    public String getNom() {
        return this.updateNomUser.getText();
    }

    public String getIdentifiant() {
        return this.updateIdentifiantUser.getText();
    }

    public String getMotDePasse() {
        return this.updateMotDePasseUser.getText();
    }

    public String getAdresseEmail() {
        return this.updateAdresseMailUser.getText();
    }

    //Set
    public void setID(int id) {
        this.id = id;
    }

    public void setPrenom(String prenom) {
        this.updatePrenomUser.setText(prenom);
    }

    public void setNom(String nom) {
        this.updateNomUser.setText(nom);
    }

    public void setIdentifiant(String identifiant) {
        this.updateIdentifiantUser.setText(identifiant);;
    }

    public void setMotDePasse(String mdp) {
        this.updateMotDePasseUser.setText(mdp);
    }

    public void setAdresseEmail(String email) {
        this.updateAdresseMailUser.setText(email);
    }

    /**
     * Creates new form UpdateUserJDialog
     */
    public UpdateUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRetour = new javax.swing.JButton();
        jLabelPrenomUser = new javax.swing.JLabel();
        jLabelNomUser = new javax.swing.JLabel();
        jLabelIdentifiantUser = new javax.swing.JLabel();
        jLabelMotDePasseUser = new javax.swing.JLabel();
        jLabelAdresseEmailUser = new javax.swing.JLabel();
        jButtonValiderModif = new javax.swing.JButton();
        updatePrenomUser = new javax.swing.JTextField();
        updateIdentifiantUser = new javax.swing.JTextField();
        updateMotDePasseUser = new javax.swing.JTextField();
        updateNomUser = new javax.swing.JTextField();
        updateAdresseMailUser = new javax.swing.JTextField();
        jLabelPageModifUtilisateur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jLabelPrenomUser.setText("Prenom");

        jLabelNomUser.setText("Nom");

        jLabelIdentifiantUser.setText("Identifiant");

        jLabelMotDePasseUser.setText("Mot-de-passe");

        jLabelAdresseEmailUser.setText("Adresse mail");

        jButtonValiderModif.setText("Valider");
        jButtonValiderModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderModifActionPerformed(evt);
            }
        });

        updatePrenomUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePrenomUserActionPerformed(evt);
            }
        });

        updateMotDePasseUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMotDePasseUserActionPerformed(evt);
            }
        });

        updateNomUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNomUserActionPerformed(evt);
            }
        });

        updateAdresseMailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAdresseMailUserActionPerformed(evt);
            }
        });

        jLabelPageModifUtilisateur.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelPageModifUtilisateur.setText("Page Modif Utilisateur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPrenomUser)
                            .addComponent(jLabelNomUser)
                            .addComponent(jLabelIdentifiantUser)
                            .addComponent(jLabelMotDePasseUser)
                            .addComponent(jLabelAdresseEmailUser))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateIdentifiantUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updatePrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateAdresseMailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonValiderModif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRetour))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabelPageModifUtilisateur)))
                .addGap(0, 171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabelPageModifUtilisateur)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenomUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateIdentifiantUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdentifiantUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotDePasseUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateAdresseMailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdresseEmailUser))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValiderModif)
                    .addComponent(jButtonRetour))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButtonValiderModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderModifActionPerformed
        listeners.firePropertyChange("validModif", null, null);
    }//GEN-LAST:event_jButtonValiderModifActionPerformed

    private void updateAdresseMailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAdresseMailUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateAdresseMailUserActionPerformed

    private void updateNomUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNomUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateNomUserActionPerformed

    private void updateMotDePasseUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMotDePasseUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMotDePasseUserActionPerformed

    private void updatePrenomUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePrenomUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePrenomUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateUserDialog dialog = new UpdateUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValiderModif;
    private javax.swing.JLabel jLabelAdresseEmailUser;
    private javax.swing.JLabel jLabelIdentifiantUser;
    private javax.swing.JLabel jLabelMotDePasseUser;
    private javax.swing.JLabel jLabelNomUser;
    private javax.swing.JLabel jLabelPageModifUtilisateur;
    private javax.swing.JLabel jLabelPrenomUser;
    private javax.swing.JTextField updateAdresseMailUser;
    private javax.swing.JTextField updateIdentifiantUser;
    private javax.swing.JTextField updateMotDePasseUser;
    private javax.swing.JTextField updateNomUser;
    private javax.swing.JTextField updatePrenomUser;
    // End of variables declaration//GEN-END:variables
}
